title: JPGO
description: A practical guide for overseas brands entering the Japanese market
theme: minima
lang: en

author: Yuto Saeki

header_pages:
  - learn.md
  - research.md
  - work.md

plugins:
  - jekyll-feed
